# Generated by Django 5.2.8 on 2025-11-11 12:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дополнительное к товарам',
                'verbose_name_plural': 'Дополнительные к товарам',
            },
        ),
        migrations.CreateModel(
            name='GameKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.CharField(help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')", max_length=50, verbose_name='Выделенный текст')),
                ('normal_text', models.CharField(help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')", max_length=200, verbose_name='Обычный текст')),
            ],
            options={
                'verbose_name': 'Элемент комплектации',
                'verbose_name_plural': 'Элементы комплектации',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид игры')),
            ],
            options={
                'verbose_name': 'Вид игры',
                'verbose_name_plural': 'Виды игр',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PlayerAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст игроков')),
            ],
            options={
                'verbose_name': 'Возраст игрока',
                'verbose_name_plural': 'Возрасты игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество игроков')),
            ],
            options={
                'verbose_name': 'Количество игроков',
                'verbose_name_plural': 'Количество игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.PositiveIntegerField(verbose_name='Минимальное количество игроков')),
                ('max_players', models.PositiveIntegerField(verbose_name='Максимальное количество игроков')),
                ('min_game_count', models.PositiveIntegerField(verbose_name='Минимальное количество игр')),
                ('max_game_count', models.PositiveIntegerField(verbose_name='Максимальное количество игр')),
            ],
            options={
                'verbose_name': 'Диапазон игроков',
                'verbose_name_plural': 'Диапазоны игроков',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_product_images/additional/', verbose_name='Дополнительное изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('additional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.additionalproducts', verbose_name='Допы к товару')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение допов товара',
                'verbose_name_plural': 'Дополнительные изображения допов товара',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/additional/', verbose_name='Дополнительное изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение новости',
                'verbose_name_plural': 'Дополнительные изображения новостей',
            },
        ),
        migrations.CreateModel(
            name='Arenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название аренды')),
                ('game_count', models.PositiveIntegerField(default=6, verbose_name='Количество игр в аренде')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ranges', models.ManyToManyField(blank=True, to='core.playerrange', verbose_name='Диапазоны игроков и игр')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game_rules', models.TextField(blank=True, help_text='Введите правила игры. Каждый новый пункт будет отображаться с новой строки.', null=True, verbose_name='Правила игры')),
                ('additional_info', models.TextField(blank=True, help_text='Введите дополнительную информацию. Каждый новый пункт будет отображаться с новой строки.', null=True, verbose_name='Дополнительно')),
                ('game_kit_items', models.ManyToManyField(blank=True, related_name='products', to='core.gamekititem', verbose_name='Элементы комплектации')),
                ('game_types', models.ManyToManyField(blank=True, to='core.gametype', verbose_name='Виды игры')),
                ('player_ages', models.ManyToManyField(blank=True, to='core.playerage', verbose_name='Возрасты игроков')),
                ('player_counts', models.ManyToManyField(blank=True, to='core.playercount', verbose_name='Количество игроков')),
                ('sizes', models.ManyToManyField(blank=True, to='core.size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('order_type', models.CharField(choices=[('buy', 'Купить'), ('rent', 'Аренда')], max_length=10, verbose_name='Тип заказа')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата заказа')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='Время заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('additional_products', models.ManyToManyField(blank=True, related_name='order_additional_products', to='core.additionalproducts', verbose_name='Дополнительные товары')),
                ('arenda', models.ManyToManyField(blank=True, related_name='order_arenda', to='core.arenda', verbose_name='Выбранные аренды')),
                ('games_for_rent', models.ManyToManyField(blank=True, related_name='order_games_for_rent', to='core.product', verbose_name='Игры для аренды')),
                ('products', models.ManyToManyField(blank=True, related_name='order_products', to='core.product', verbose_name='Выбранные товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/additional/', verbose_name='Дополнительное изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение товара',
                'verbose_name_plural': 'Дополнительные изображения товаров',
            },
        ),
    ]
