# Generated by Django 5.2.8 on 2025-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekititem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='gamekititem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gamekititem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='highlighted_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='normal_text',
            field=models.CharField(max_length=255),
        ),
    ]
