# Generated by Django 5.2.8 on 2025-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamekititem_options_gamekititem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekititem',
            options={},
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='highlighted_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='normal_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
