# Generated by Django 5.2.8 on 2025-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gamekititem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekititem',
            options={'verbose_name': 'Элемент комплектации', 'verbose_name_plural': 'Элементы комплектации'},
        ),
        migrations.RemoveField(
            model_name='gamekititem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gamekititem',
            name='order',
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='highlighted_text',
            field=models.CharField(help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')", max_length=50, verbose_name='Выделенный текст'),
        ),
        migrations.AlterField(
            model_name='gamekititem',
            name='normal_text',
            field=models.CharField(help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')", max_length=200, verbose_name='Обычный текст'),
        ),
    ]
