# Generated by Django 5.2.8 on 2025-11-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gamekititem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedGameKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('game_kit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamekititem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_game_kits', to='core.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
