# Generated by Django 5.2 on 2025-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderedgamekititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='engraving',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, verbose_name='Гравировка'),
        ),
    ]
