# Generated by Django 5.2 on 2025-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_delivery_address_order_engraving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процентная'), ('fixed', 'Фиксированная')], default='percentage', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение скидки')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('additional_products', models.ManyToManyField(blank=True, related_name='discounts', to='core.additionalproducts', verbose_name='Дополнительные товары')),
                ('arendas', models.ManyToManyField(blank=True, related_name='discounts', to='core.arenda', verbose_name='Аренды')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='core.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-start_date'],
            },
        ),
    ]
