# Generated by Django 5.2.8 on 2025-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenda',
            name='time',
            field=models.PositiveIntegerField(default=120, verbose_name='Время в минутах'),
        ),
    ]
