# Generated by Django 5.2.8 on 2025-12-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_arenda_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenda',
            name='time',
            field=models.CharField(default=2, verbose_name='Время в часах'),
        ),
    ]
