# Generated by Django 5.2 on 2025-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_arenda_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenda',
            name='card_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Стиль 1 (оранжевый)'), (2, 'Стиль 2 (альтернативный)')], default=1, verbose_name='Стиль карточки'),
        ),
    ]
