# Generated by Django 5.2.8 on 2025-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_arenda_card_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenda',
            name='is_specific_game',
            field=models.BooleanField(default=False, verbose_name='Аренда конкретной игры'),
        ),
    ]
