# Generated by Django 5.2.8 on 2025-12-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_arenda_is_specific_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenda',
            name='specific_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
