# Generated by Django 5.2.8 on 2025-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_arenda_specific_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameKitItemAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.CharField(help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')", max_length=50, verbose_name='Выделенный текст')),
                ('normal_text', models.CharField(help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')", max_length=200, verbose_name='Обычный текст')),
            ],
            options={
                'verbose_name': 'Элемент комплектации',
                'verbose_name_plural': 'Элементы комплектации',
            },
        ),
        migrations.AddField(
            model_name='additionalproducts',
            name='description_2',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='order',
            name='double_game_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 игра'), (2, '2 игры')], default=1, verbose_name='Количество игр на одной доске'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Купить'), ('rent', 'Аренда'), ('double_buy', 'Купить 2 игры на одной доске')], max_length=10, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='additionalproducts',
            name='game_kit_items_additional',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.gamekititemadditional', verbose_name='Элементы комплектации'),
        ),
    ]
