# Generated by Django 5.2.8 on 2025-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gamekititemadditional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekititemadditional',
            options={'verbose_name': 'Элемент комплектации для допов', 'verbose_name_plural': 'Элементы комплектации для допов'},
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='description_2',
            field=models.TextField(default='', verbose_name='Описание_2'),
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='game_kit_items_additional',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.gamekititemadditional', verbose_name='Элементы комплектации для допов'),
        ),
        migrations.AlterField(
            model_name='gamekititemadditional',
            name='highlighted_text',
            field=models.TextField(help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')", max_length=50, verbose_name='Выделенный текст'),
        ),
        migrations.AlterField(
            model_name='gamekititemadditional',
            name='normal_text',
            field=models.TextField(help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')", max_length=200, verbose_name='Обычный текст'),
        ),
    ]
