# Generated by Django 5.2.8 on 2025-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_gamekititemadditional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='material',
            field=models.TextField(default='', max_length=200, verbose_name='Материал'),
        ),
    ]
