# Generated by Django 5.2 on 2025-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_additionalproducts_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='button_text_type',
            field=models.CharField(choices=[('material', 'МАТЕРИАЛ'), ('additional', 'ДОПОЛНИТЕЛЬНО')], default='material', help_text="Выберите текст для кнопки: 'МАТЕРИАЛ' или 'ДОПОЛНИТЕЛЬНО'", max_length=10, verbose_name='Тип текста кнопки'),
        ),
    ]
