# Generated by Django 5.2 on 2025-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_additionalproducts_button_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='price_prefix',
            field=models.CharField(default='от', max_length=10, verbose_name='Приставка к цене'),
        ),
    ]
