# Generated by Django 5.2 on 2025-12-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_additionalproducts_price_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproducts',
            name='price_prefix',
            field=models.CharField(blank=True, default='от', max_length=10, null=True, verbose_name='Приставка к цене'),
        ),
    ]
