# Generated by Django 5.2.8 on 2025-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_additionalproducts_price_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='material_html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML-материал'),
        ),
    ]
