# Generated by Django 5.2.8 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_additionalproducts_material_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='description_2_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание_2 (HTML)'),
        ),
        migrations.AddField(
            model_name='additionalproducts',
            name='description_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание (HTML)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание (HTML)'),
        ),
        migrations.AddField(
            model_name='product',
            name='game_rules_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Правила игры (HTML)'),
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='description_2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание_2'),
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='material',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='additionalproducts',
            name='material_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='HTML-материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='game_rules',
            field=models.TextField(blank=True, default='', help_text='Введите правила игры. Каждый новый пункт будет отображаться с новой строки.', null=True, verbose_name='Правила игры'),
        ),
    ]
