# Generated by Django 5.2.8 on 2025-12-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_additionalproducts_description_2_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproducts',
            name='button_text_type',
        ),
        migrations.RemoveField(
            model_name='additionalproducts',
            name='description_2_html',
        ),
        migrations.RemoveField(
            model_name='additionalproducts',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='additionalproducts',
            name='material_html',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='product',
            name='game_rules_html',
        ),
    ]
