# Generated by Django 5.2.8 on 2025-12-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_additionalproducts_button_text_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание скидки, которое будет отображаться на сайте', null=True, verbose_name='Описание скидки'),
        ),
    ]
