# Generated by Django 5.2.8 on 2025-12-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_discount_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название плашки')),
                ('badge_type', models.CharField(choices=[('new', 'Новинка'), ('in_stock', 'В наличии')], default='new', max_length=10, verbose_name='Тип плашки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('additional_products', models.ManyToManyField(blank=True, related_name='badges', to='core.additionalproducts', verbose_name='Дополнительные товары')),
                ('arendas', models.ManyToManyField(blank=True, related_name='badges', to='core.arenda', verbose_name='Аренды')),
                ('products', models.ManyToManyField(blank=True, related_name='badges', to='core.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Плашка',
                'verbose_name_plural': 'Плашки',
            },
        ),
    ]
