# Generated by Django 5.2.8 on 2025-12-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_badge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
