# Generated by Django 5.2.8 on 2025-12-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='additionalproducts',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='arenda',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='arenda',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
