# Generated by Django 5.2 on 2025-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_additionalproducts_is_in_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('last_order_time', models.DateTimeField(verbose_name='Время последней заявки')),
            ],
            options={
                'verbose_name': 'Ограничение на отправку заявок',
                'verbose_name_plural': 'Ограничения на отправку заявок',
            },
        ),
    ]
