# Generated by Django 5.2.8 on 2025-12-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ordercooldown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCooldown',
        ),
    ]
