# Generated by Django 5.2 on 2026-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_ordercooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenda',
            name='time',
            field=models.CharField(default=2, max_length=100, verbose_name='Время в часах'),
        ),
    ]
