# Generated by Django 5.2 on 2026-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_arenda_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Это спам?'),
        ),
    ]
