# Generated by Django 5.2 on 2026-01-10 15:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_order_ip_address_order_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekititem',
            name='highlighted_text',
            field=models.CharField(
                max_length=50,
                verbose_name='Выделенный текст',
                help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')",
                default='',
            ),
        ),
        migrations.AddField(
            model_name='gamekititem',
            name='normal_text',
            field=models.CharField(
                max_length=200,
                verbose_name='Обычный текст',
                help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')",
                default='',
            ),
        ),
    ]
