# Generated by Django 5.2 on 2026-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_gamekititem_highlighted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Цена по договорённости'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
