# Generated by Django 5.2 on 2026-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_is_price_negotiable"),
    ]
    operations = [
        migrations.AlterField(
            model_name="arenda",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Изображение"
            ),
        ),
    ]
