# Generated by Django 5.2 on 2026-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_arenda_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше позиция в каталоге', verbose_name='Порядок отображения'),
        ),
    ]
