# Generated by Django 5.2 on 2026-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducts',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше позиция в каталоге', verbose_name='Порядок отображения'),
        ),
    ]
